env:
  IMAGE_TAG: 39
  GITHUB_SERVER_URL: "https://github.com"
  CIRRUS_SHELL: bash
  IMAGE_SUFFIX: "c20240227t125812z-f39f38d13"
  FEDORA_AARCH64_AMI: "fedora-podman-aws-arm64-${IMAGE_SUFFIX}"

aws_credentials: ENCRYPTED[1625a7241b4d8c8b56fab6419ba3cd6969f44c854568d12166cb9a32688784c5cc4570d7e3d9c4f03d143e275a50b819]

build_task:
  alias: 'build'
  only_if: $CIRRUS_BRANCH == 'main' && $CIRRUS_PR == "" && $CIRRUS_TAG == ""
  #execution_lock: podman-wsl-fedora-arm-serial
  auto_cancellation: true
  ec2_instance: &standard_build_ec2_aarch64
    image: ${FEDORA_AARCH64_AMI}
    type: "t4g.xlarge"
    region: us-east-1
    architecture: arm64
  main_script: |
    echo "Hello World"
